### ISSUE TITLE
Timeout in anupqeg.tst

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/anupq#5] opened 2014-10-13 16:30 UTC
This has been observed in Jenkins when GAP is compiled in 32-bit mode without GMP on OS X machine using the default compiler provided by XCode, reporting itself as `(Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)`. This may be seen, for example, in [this Jenkins build](https://keith.cs.st-andrews.ac.uk:8443/view/GAP%20release/job/GAP-minor-release-test/161/GAPCOPTS=32build,GAPGMP=nogmp,GAPTARGET=packages,label=fruitloop/consoleFull). Trying to reproduce it interactively with `Test("anupqeg.tst",rec(showProgress:=true));` I suppose that it hangs on the following example:

```
# line 47208, input:
##Example: "Nott-APG-Rel-i" . . . based on: examples/pga_interactive
# line 47209, input:
##Start point for Nottingham group
# line 47210, input:
##Interactive construction of 40 5-groups of order 5^7
# line 47211, input:
F := FreeGroup("a", "b");
# line 47213, input:
rels := ["a^5", "b^5", "[b, a, b]"];
# line 47215, input:
procId := PqStart(F : Prime := 5, Relators := rels);
# line 47217, input:
PqPcPresentation(procId : ClassBound := 3, 
                          OutputLevel := 1);
# line 47223, input:
PqComputePCover(procId);
# line 47225, input:
PqSavePcPresentation(procId, ANUPQData.outfile);
# line 47226, input:
PqPGSupplyAutomorphisms(procId, [ [[1,0,0,0],
                                   [0,1,0,1]],

                                  [[1,1,0,0],
                                   [0,1,0,1]],

                                  [[1,0,0,0],
                                   [0,4,0,0]],

                                  [[1,0,0,0],
                                   [0,2,0,0]],

                                  [[4,0,0,0],
                                   [0,1,0,0]],

                                  [[2,0,0,0],
                                   [0,1,0,0]] ]);
# line 47243, input:
PqPGConstructDescendants(procId : ClassBound := 4,
                                  CapableDescendants,
                                  StepSize := 1,
                                  PcgsAutomorphisms,
                                  RankInitialSegmentSubgroups := 4);
# line 47257, input:
PqPGSetDescendantToPcp(procId, 4, 1);
# line 47258, input:
PqAPGDegree(procId, 2, 3);
# line 47261, input:
PqAPGPermutations(procId);
# line 47262, input:
PqAPGOrbits(procId : CustomiseOutput := rec(orbit := [1]));
# line 47268, input:
PqAPGOrbitRepresentatives(procId);
# line 47269, input:
PqPGSetDescendantToPcp(procId);
# line 47270, input:
PqDisplayPcPresentation(procId);
# line 47297, input:
PqAPGSingleStage(procId : StepSize:=2, BasicAlgorithm, 
                          CustomiseOutput := rec());
```

**Comment by fingolfin** [comment] 2017-11-30 10:55
Duplicate of issue #19 (or the other way around, whatever :-).

**Closed by fingolfin** 2017-11-30 10:55 UTC
