### ISSUE TITLE
Standard test runs out of time for 32bit build on OS X (GAP compiled without GMP)

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/anupq#12] opened 2015-09-27 22:17 UTC
Just to document that for some time already I am observing that the standard test for ANUPQ runs out of time on OS X when GAP is built in 32-bit mode without GMP support:

```
Testing anupq 3.1.1, test=/Volumes/hudson-fs/workspace/GAP-dev-testpackages/GAPCOPTS/32build/GAPGMP/nogmp/GAPTARGET/packages/label/fruitloop/GAP-git-snapshot/pkg/anupq-3.1.1/tst/anupqeg.tst, all packages=false
Build timed out (after 780 minutes). Marking the build as failed.
make: *** [testpackages] Terminated: 15
Notifying upstream projects of job completion
Finished: ABORTED
```

**Comment by fingolfin** [comment] 2017-11-30 10:58
This is another duplicate of issue #19.

**Closed by fingolfin** 2017-11-30 10:58 UTC
